/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          orange: 'var(--brand-orange, #FF7A00)',
          'orange-hover': 'var(--brand-orange-hover, #EA6700)',
          yellow: 'var(--brand-yellow, #FFC400)',
          amber: 'var(--brand-amber, #FFB000)',
          soft: 'var(--brand-soft, #FFF1D6)',
          50: 'var(--color-primary-soft, #FFF1D6)',
          100: '#FFE2B8',
          200: '#FFC880',
          300: '#FFAB48',
          400: '#FF9120',
          500: '#FF7A00',
          600: 'var(--color-primary, #FF7A00)',
          700: 'var(--color-primary-hover, #EA6700)',
          800: '#C75700',
          900: '#8A3B00',
          950: '#4A1E00',
          DEFAULT: 'var(--color-primary, #FF7A00)',
          hover: 'var(--color-primary-hover, #EA6700)',
          pressed: 'var(--color-primary-pressed, #D95F00)',
          'soft-strong': 'var(--color-primary-soft-strong, rgba(255, 122, 0, 0.22))',
        },
        growth: {
          DEFAULT: 'var(--color-success, #22C55E)',
          soft: 'var(--color-success-soft, rgba(34, 197, 94, 0.10))',
        },
        theme: {
          bg: 'var(--bg-app, #F8FAFC)',
          sidebar: 'var(--bg-sidebar, #0D121C)',
          surface: 'var(--surface-1, #FFFFFF)',
          card: 'var(--surface-2, #FFFFFF)',
          'surface-hover': 'var(--surface-hover, #FFF8EE)',
          'surface-secondary': 'var(--surface-2, #FFF8EE)',
          'surface-elevated': 'var(--surface-1, #FFFFFF)',
          'text-primary': 'var(--text-primary, #111827)',
          'text-secondary': 'var(--text-secondary, #475569)',
          'text-muted': 'var(--text-muted, #64748B)',
          'text-subtle': 'var(--text-subtle, #94A3B8)',
          border: 'var(--border-subtle, #E5E7EB)',
          'border-strong': 'var(--border-strong, #CBD5E1)',
          primary: 'var(--accent, #FF7A00)',
          'primary-hover': 'var(--accent-hover, #EA6700)',
          'primary-soft': 'var(--accent-soft, #FFF1D6)',
          accent: 'var(--accent, #FF7A00)',
          'accent-soft': 'var(--accent-soft, #FFF1D6)',
          'accent-border': 'var(--accent-border, rgba(255, 122, 0, 0.30))',
          success: 'var(--success, #22C55E)',
          'success-soft': 'var(--success-soft, rgba(34, 197, 94, 0.10))',
          warning: 'var(--warning, #F59E0B)',
          danger: 'var(--danger, #EF4444)',
        },
      },
      borderRadius: {
        'card': '16px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
      },
      boxShadow: {
        'subtle': '0 1px 3px 0 rgba(0, 0, 0, 0.05), 0 1px 2px -1px rgba(0, 0, 0, 0.05)',
        'card': '0 4px 20px rgba(17, 24, 39, 0.05)',
        'elevated': '0 12px 36px -4px rgba(0, 0, 0, 0.25)',
      },
    },
  },
  plugins: [],
}
