/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          50: 'var(--color-primary-soft, #EFEDFF)',
          100: '#E4E0FF',
          200: '#C7C0FF',
          300: '#AAA0FF',
          400: '#8B7CF6',
          500: '#6C5CE7',
          600: 'var(--color-primary, #6C5CE7)',
          700: 'var(--color-primary-hover, #5B4BD8)',
          800: 'var(--color-primary-pressed, #4C3FC7)',
          900: '#372AA4',
          950: '#272344',
          DEFAULT: 'var(--color-primary, #6C5CE7)',
          hover: 'var(--color-primary-hover, #5B4BD8)',
          pressed: 'var(--color-primary-pressed, #4C3FC7)',
          soft: 'var(--color-primary-soft, #EFEDFF)',
          'soft-strong': 'var(--color-primary-soft-strong, #E4E0FF)',
        },
        growth: {
          DEFAULT: 'var(--color-accent, #22C55E)',
          soft: 'var(--color-accent-soft, #DCFCE7)',
        },
        theme: {
          bg: 'var(--color-background, #F8FAFC)',
          surface: 'var(--color-surface, #FFFFFF)',
          'surface-secondary': 'var(--color-surface-secondary, #F4F2FF)',
          'surface-elevated': 'var(--color-surface-elevated, #1D2540)',
          'text-primary': 'var(--color-text-primary, #0F172A)',
          'text-secondary': 'var(--color-text-secondary, #475569)',
          'text-muted': 'var(--color-text-muted, #64748B)',
          'text-subtle': 'var(--color-text-subtle, #94A3B8)',
          border: 'var(--color-border, #E2E8F0)',
          'border-strong': 'var(--color-border-strong, #CBD5E1)',
          primary: 'var(--color-primary, #6C5CE7)',
          'primary-hover': 'var(--color-primary-hover, #5B4BD8)',
          'primary-pressed': 'var(--color-primary-pressed, #4C3FC7)',
          'primary-soft': 'var(--color-primary-soft, #EFEDFF)',
          accent: 'var(--color-accent, #22C55E)',
          'accent-soft': 'var(--color-accent-soft, #DCFCE7)',
          success: 'var(--color-success, #16A34A)',
          warning: 'var(--color-warning, #F59E0B)',
          'warning-soft': 'var(--color-warning-soft, #FEF3C7)',
          danger: 'var(--color-danger, #EF4444)',
          'danger-soft': 'var(--color-danger-soft, #FEE2E2)',
        },
      },
      borderRadius: {
        'card': '16px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
      },
      boxShadow: {
        'subtle': '0 1px 3px 0 rgba(0, 0, 0, 0.05), 0 1px 2px -1px rgba(0, 0, 0, 0.05)',
        'card': '0 4px 6px -1px rgba(0, 0, 0, 0.04), 0 2px 4px -2px rgba(0, 0, 0, 0.04)',
        'elevated': '0 10px 15px -3px rgba(0, 0, 0, 0.08), 0 4px 6px -4px rgba(0, 0, 0, 0.04)',
      },
    },
  },
  plugins: [],
}
