-- AlterEnum
ALTER TYPE "GrowthArea" ADD VALUE 'PERSONAL';

-- AlterEnum
ALTER TYPE "GoalType" ADD VALUE 'ENGLISH_SPEAKING';
ALTER TYPE "GoalType" ADD VALUE 'PUBLIC_SPEAKING';
ALTER TYPE "GoalType" ADD VALUE 'PROFESSIONAL_COMMUNICATION';
ALTER TYPE "GoalType" ADD VALUE 'WRITING';
ALTER TYPE "GoalType" ADD VALUE 'PRESENTATION';
ALTER TYPE "GoalType" ADD VALUE 'CONFIDENCE';
ALTER TYPE "GoalType" ADD VALUE 'LANGUAGE_LEARNING';
ALTER TYPE "GoalType" ADD VALUE 'INTERVIEW_COMMUNICATION';

-- AlterEnum
ALTER TYPE "GoalType" ADD VALUE 'FITNESS';
ALTER TYPE "GoalType" ADD VALUE 'NUTRITION';
ALTER TYPE "GoalType" ADD VALUE 'SLEEP';
ALTER TYPE "GoalType" ADD VALUE 'MENTAL_WELLBEING';
ALTER TYPE "GoalType" ADD VALUE 'WEIGHT';
ALTER TYPE "GoalType" ADD VALUE 'DAILY_ACTIVITY';
ALTER TYPE "GoalType" ADD VALUE 'HEALTH_ROUTINE';

-- AlterEnum
ALTER TYPE "GoalType" ADD VALUE 'HABIT';
ALTER TYPE "GoalType" ADD VALUE 'FINANCE';
ALTER TYPE "GoalType" ADD VALUE 'RELATIONSHIP';
ALTER TYPE "GoalType" ADD VALUE 'PRODUCTIVITY';
ALTER TYPE "GoalType" ADD VALUE 'SELF_DEVELOPMENT';
ALTER TYPE "GoalType" ADD VALUE 'READING';
ALTER TYPE "GoalType" ADD VALUE 'LIFE_SKILL';
